package summarize

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net/http"
	"strings"
	"sync/atomic"
	"time"
)

// Options are the tunable Ollama generation parameters. Zero values mean
// "let Ollama pick its default" (we don't send them in the request body).
type Options struct {
	Temperature float64 `json:"temperature"`
	TopP        float64 `json:"top_p"`
	NumCtx      int     `json:"num_ctx"`
}

// Ollama summarizes via Ollama's `/api/generate` endpoint. Output is parsed
// against the labeled "SUMMARY:/POINTS:" template; legacy JSON-object,
// bare-array, and plain bullet-list shapes are handled as fallbacks. The
// active model + generation options are held in atomic values so the admin
// API can swap them at runtime without restarting the process.
type Ollama struct {
	BaseURL    string
	model      atomic.Value // string
	options    atomic.Pointer[Options]
	HTTPClient *http.Client
	// MaxInput caps the text we send (in runes) so we don't blow the context
	// window with very long articles.
	MaxInput int
}

// NewOllama constructs an Ollama summarizer. Both URL and model are required.
func NewOllama(baseURL, model string) *Ollama {
	o := &Ollama{
		BaseURL: strings.TrimRight(baseURL, "/"),
		HTTPClient: &http.Client{
			// Ollama's API never redirects. Refuse to follow one so a
			// misconfigured or compromised base URL can't bounce the request
			// to an internal address. We deliberately don't apply the private-
			// IP SSRF block here: the base URL is admin-set and commonly points
			// at localhost/LAN Ollama, which that block would break.
			//
			// No client-level Timeout: the caller owns the deadline. The poller
			// derives one context deadline per article from the configurable
			// summary_timeout_seconds setting and it covers Summarize's internal
			// retry, so a timed-out article is abandoned once instead of being
			// regenerated by the backend on attempt 2 (issue #201). The admin
			// endpoints below pass their own bounded contexts.
			CheckRedirect: func(*http.Request, []*http.Request) error {
				return errors.New("ollama: unexpected redirect")
			},
		},
		MaxInput: 8000,
	}
	o.model.Store(model)
	return o
}

// fallbackHTTPClient serves an Ollama built without NewOllama (tests, or a
// zero-value struct). Shared and never mutated. No Timeout — every caller
// passes a bounded context.
var fallbackHTTPClient = &http.Client{}

// client returns the effective HTTP client WITHOUT assigning to o.HTTPClient.
// Summarize used to lazily initialise the field, which is a write to a struct
// the admin endpoints (ListInstalled/Delete/Pull) read from HTTP handlers at
// the same time as the poller's summary worker calls Summarize — a data race,
// and a nil-pointer panic for whichever read lost. model and options are held
// in atomics for precisely this reason; the client needs the same care.
func (o *Ollama) client() *http.Client {
	if o.HTTPClient != nil {
		return o.HTTPClient
	}
	return fallbackHTTPClient
}

// Model returns the currently active model name. NewOllama always stores
// a string into o.model (possibly ""), so Load is never nil here.
func (o *Ollama) Model() string {
	v, _ := o.model.Load().(string)
	return v
}

// SetModel atomically swaps the active model. Used by the admin API to switch
// models at runtime. Empty string is allowed (Summarize will then error).
func (o *Ollama) SetModel(name string) {
	o.model.Store(name)
}

// Options returns the currently active generation tunables. Zero-valued
// fields mean "use Ollama defaults".
func (o *Ollama) Options() Options {
	if p := o.options.Load(); p != nil {
		return *p
	}
	return Options{}
}

// SetOptions atomically swaps the generation tunables for future Summarize
// calls. Pass a zero Options to clear all tuning.
func (o *Ollama) SetOptions(opts Options) {
	o.options.Store(&opts)
}

// InstalledModel is one entry from Ollama's /api/tags.
type InstalledModel struct {
	Name       string `json:"name"`
	SizeBytes  int64  `json:"size_bytes"`
	ModifiedAt string `json:"modified_at"`
}

// ListInstalled queries Ollama's /api/tags and returns the locally-cached
// models. Used by the admin UI to populate the model picker.
func (o *Ollama) ListInstalled(ctx context.Context) ([]InstalledModel, error) {
	if o.BaseURL == "" {
		return nil, errors.New("summarize: ollama url not configured")
	}
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, o.BaseURL+"/api/tags", nil)
	if err != nil {
		return nil, err
	}
	resp, err := o.client().Do(req)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		return nil, fmt.Errorf("summarize: ollama tags status %d", resp.StatusCode)
	}
	var body struct {
		Models []struct {
			Name       string `json:"name"`
			Size       int64  `json:"size"`
			ModifiedAt string `json:"modified_at"`
		} `json:"models"`
	}
	if err := json.NewDecoder(io.LimitReader(resp.Body, 1<<20)).Decode(&body); err != nil {
		return nil, err
	}
	out := make([]InstalledModel, 0, len(body.Models))
	for _, m := range body.Models {
		out = append(out, InstalledModel{Name: m.Name, SizeBytes: m.Size, ModifiedAt: m.ModifiedAt})
	}
	return out, nil
}

// Delete removes a model from Ollama's local cache via DELETE /api/delete.
// Returns an error if Ollama refuses (e.g. unknown model) or if it can't be
// reached.
func (o *Ollama) Delete(ctx context.Context, name string) error {
	if o.BaseURL == "" {
		return errors.New("summarize: ollama url not configured")
	}
	// Model deletion is a local metadata operation; bound it so an unreachable
	// Ollama can't wedge an admin request now that the client has no timeout.
	ctx, cancel := context.WithTimeout(ctx, 30*time.Second)
	defer cancel()
	body, err := json.Marshal(map[string]any{"name": name})
	if err != nil {
		return err
	}
	req, err := http.NewRequestWithContext(ctx, http.MethodDelete, o.BaseURL+"/api/delete", bytes.NewReader(body))
	if err != nil {
		return err
	}
	req.Header.Set("Content-Type", "application/json")
	resp, err := o.client().Do(req)
	if err != nil {
		return err
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		return statusError("delete", resp)
	}
	return nil
}

// Pull triggers `ollama pull <model>`. Blocks until done (or ctx is cancelled).
// Returns the response body for diagnostic logging; the caller decides what
// to surface to the UI.
func (o *Ollama) Pull(ctx context.Context, name string) error {
	if o.BaseURL == "" {
		return errors.New("summarize: ollama url not configured")
	}
	body, err := json.Marshal(map[string]any{"name": name, "stream": false})
	if err != nil {
		return err
	}
	// Long-running operation: reuse the configured transport (so custom
	// proxies / TLS / mTLS still apply) but override the timeout. Default
	// Summarize timeout is 90s; pulling a multi-GB model can take 30 min.
	client := &http.Client{Transport: o.client().Transport, Timeout: 30 * time.Minute}
	req, err := http.NewRequestWithContext(ctx, http.MethodPost, o.BaseURL+"/api/pull", bytes.NewReader(body))
	if err != nil {
		return err
	}
	req.Header.Set("Content-Type", "application/json")
	resp, err := client.Do(req)
	if err != nil {
		return err
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		return statusError("pull", resp)
	}
	// Drain to confirm the pull completed.
	_, _ = io.Copy(io.Discard, io.LimitReader(resp.Body, 64*1024))
	return nil
}

// statusError builds the error for a non-200 Ollama response, including a
// bounded snippet of the body so the admin UI can show why it was refused.
func statusError(op string, resp *http.Response) error {
	raw, _ := io.ReadAll(io.LimitReader(resp.Body, 4096))
	return fmt.Errorf("summarize: ollama %s status %d: %s", op, resp.StatusCode, strings.TrimSpace(string(raw)))
}

type generateRequest struct {
	Model   string         `json:"model"`
	Prompt  string         `json:"prompt"`
	Stream  bool           `json:"stream"`
	Options map[string]any `json:"options,omitempty"`
}

type generateResponse struct {
	Response string `json:"response"`
	Done     bool   `json:"done"`
}

// Summarize calls Ollama and parses the response into a Result.
func (o *Ollama) Summarize(ctx context.Context, title, text string) (Result, string, error) {
	model := o.Model()
	if o.BaseURL == "" || model == "" {
		return Result{}, "", errors.New("summarize: ollama url/model not configured")
	}
	maxInput := o.MaxInput
	if maxInput == 0 {
		maxInput = DefaultMaxInput
	}
	req := generateRequest{
		Model:  model,
		Prompt: BuildPrompt(title, text, maxInput),
		Stream: false,
	}
	opts := o.Options()
	if opts.Temperature > 0 || opts.TopP > 0 || opts.NumCtx > 0 {
		req.Options = map[string]any{}
		if opts.Temperature > 0 {
			req.Options["temperature"] = opts.Temperature
		}
		if opts.TopP > 0 {
			req.Options["top_p"] = opts.TopP
		}
		if opts.NumCtx > 0 {
			req.Options["num_ctx"] = opts.NumCtx
		}
	}
	body, err := json.Marshal(req)
	if err != nil {
		return Result{}, model, err
	}

	// One retry on transient errors.
	var lastErr error
	for attempt := range 2 {
		res, err := o.tryOnce(ctx, body)
		if err == nil {
			return res, model, nil
		}
		lastErr = err
		if ctx.Err() != nil {
			return Result{}, model, ctx.Err()
		}
		if attempt == 0 {
			select {
			case <-time.After(250 * time.Millisecond):
			case <-ctx.Done():
				return Result{}, model, ctx.Err()
			}
		}
	}
	return Result{}, model, lastErr
}

func (o *Ollama) tryOnce(ctx context.Context, body []byte) (Result, error) {
	req, err := http.NewRequestWithContext(ctx, http.MethodPost, o.BaseURL+"/api/generate", bytes.NewReader(body))
	if err != nil {
		return Result{}, err
	}
	req.Header.Set("Content-Type", "application/json")
	resp, err := o.client().Do(req)
	if err != nil {
		return Result{}, err
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		return Result{}, fmt.Errorf("summarize: ollama status %d", resp.StatusCode)
	}
	raw, err := io.ReadAll(io.LimitReader(resp.Body, 1<<20))
	if err != nil {
		return Result{}, err
	}
	var gr generateResponse
	if err := json.Unmarshal(raw, &gr); err != nil {
		return Result{}, fmt.Errorf("summarize: decode ollama response: %w", err)
	}
	return ParseResult(gr.Response)
}
